### ISSUE TITLE
Warning: Declaration of CRM_Mailchimp_Permission

### ISSUE THREAD

**Issue by palur76** [veda-consulting-company/uk.co.vedaconsulting.mailchimp#345]
Warning: Declaration of CRM_Mailchimp_Permission::check($permissions) should be compatible with CRM_Core_Permission::check($permissions, $contactId = NULL) in require_once() (line 220 of /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/ClassLoader.php).

PHP version: 7.3.19-1~deb10u1, 
CiviCRM version: 5.34.0, 
Mailchimp integration version: 2.0.1

Warning: Declaration of CRM_Mailchimp_Permission::check($permissions) should be compatible with CRM_Core_Permission::check($permissions, $contactId = NULL) üzenet require_once() függvényben (/var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/ClassLoader.php 220. sorában)

#0 /var/www/devweb/web/core/includes/bootstrap.inc(305): _drupal_error_handler_real(2, 'Declaration of ...', '/var/www/devweb...', 0)
#1 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/ClassLoader.php(220): _drupal_error_handler(2, 'Declaration of ...', '/var/www/devweb...', 0, Array)
#2 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/ClassLoader.php(220): require_once()
#3 [internal function]: CRM_Core_ClassLoader->loadClass('CRM_Mailchimp_P...')
#4 /var/www/devweb/web/sites/default/custom_ext/uk.co.vedaconsulting.mailchimp/mailchimp.php(407): spl_autoload_call('CRM_Mailchimp_P...')
#5 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(271): mailchimp_civicrm_permission(Array)
#6 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Utils/Hook/DrupalBase.php(73): CRM_Utils_Hook->runHooks(Array, 'civicrm_permiss...', 1, Array, NULL, NULL, NULL, NULL, NULL)
#7 /var/www/devweb/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(168): CRM_Utils_Hook_DrupalBase->invokeViaUF(1, Array, NULL, NULL, NULL, NULL, NULL, 'civicrm_permiss...')
#8 /var/www/devweb/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), 'hook_civicrm_pe...', Object(Civi\Core\CiviEventDispatcher))
#9 /var/www/devweb/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'hook_civicrm_pe...', Object(Civi\Core\Event\GenericHookEvent))
#10 /var/www/devweb/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'hook_civicrm_pe...', Object(Civi\Core\Event\GenericHookEvent))
#11 /var/www/devweb/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Civi\Core\Event\GenericHookEvent), Object(Civi\Core\Event\GenericHookEvent))
#12 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(167): Civi\Core\CiviEventDispatcher->dispatch('hook_civicrm_pe...', Object(Civi\Core\Event\GenericHookEvent))
#13 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(2036): CRM_Utils_Hook->invoke(Array, Array, NULL, NULL, NULL, NULL, NULL, 'civicrm_permiss...')
#14 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/Permission/Base.php(271): CRM_Utils_Hook::permission(Array)
#15 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/Permission.php(633): CRM_Core_Permission_Base->getAllModulePermissions(true)
#16 /var/www/devweb/vendor/civicrm/civicrm-core/CRM/Core/Permission.php(577): CRM_Core_Permission::assembleBasicPermissions(false, true)
#17 /var/www/devweb/web/modules/contrib/civicrm/src/CivicrmPermissions.php(40): CRM_Core_Permission::basicPermissions(false, true)
#18 [internal function]: Drupal\civicrm\CivicrmPermissions->permissions()
#19 /var/www/devweb/web/core/modules/user/src/PermissionHandler.php(149): call_user_func(Array)
#20 /var/www/devweb/web/core/modules/user/src/PermissionHandler.php(108): Drupal\user\PermissionHandler->buildPermissionsYaml()
#21 /var/www/devweb/web/core/modules/user/src/Form/UserPermissionsForm.php(126): Drupal\user\PermissionHandler->getPermissions()
#22 [internal function]: Drupal\user\Form\UserPermissionsForm->buildForm(Array, Object(Drupal\Core\Form\FormState))
#23 /var/www/devweb/web/core/lib/Drupal/Core/Form/FormBuilder.php(532): call_user_func_array(Array, Array)
#24 /var/www/devweb/web/core/lib/Drupal/Core/Form/FormBuilder.php(278): Drupal\Core\Form\FormBuilder->retrieveForm('user_admin_perm...', Object(Drupal\Core\Form\FormState))
#25 /var/www/devweb/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\user\Form\UserPermissionsForm), Object(Drupal\Core\Form\FormState))
#26 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#27 /var/www/devweb/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#28 /var/www/devweb/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#29 /var/www/devweb/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#30 /var/www/devweb/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#31 /var/www/devweb/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#32 /var/www/devweb/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#33 /var/www/devweb/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /var/www/devweb/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /var/www/devweb/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /var/www/devweb/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#37 /var/www/devweb/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#38 /var/www/devweb/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#39 /var/www/devweb/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#40 /var/www/devweb/web/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#41 /var/www/devweb/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#42 {main}

.

**Comment by awasson** [comment]
This error is fixed in the code but was never committed to the release for some reason. The error is in the file CRM/Mailchimp/Permission.php on line 28. It should read:

`public static function check($permissions, $contactId = NULL) {`
